// 自动生成（ffigen）—— 请勿手改；改动请修改头文件后重新运行 ffigen。
// ignore_for_file: type=lint, unused_field, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// musicxx_extern_plugin 宿主 C ABI 绑定（自动生成）
class MusicxxExternPluginBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MusicxxExternPluginBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MusicxxExternPluginBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// 跨边界堆分配 (与 string_free 同一分配器)
  ffi.Pointer<ffi.Void> musicxx_extern_plugin_malloc(int size) {
    return _musicxx_extern_plugin_malloc(size);
  }

  late final _musicxx_extern_plugin_mallocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Uint64)>>(
        'musicxx_extern_plugin_malloc',
      );
  late final _musicxx_extern_plugin_malloc = _musicxx_extern_plugin_mallocPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int)>();

  /// 释放 musicxx_extern_plugin_malloc 分配的指针 (NULL 安全)
  void musicxx_extern_plugin_free(ffi.Pointer<ffi.Void> ptr) {
    return _musicxx_extern_plugin_free(ptr);
  }

  late final _musicxx_extern_plugin_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'musicxx_extern_plugin_free',
      );
  late final _musicxx_extern_plugin_free = _musicxx_extern_plugin_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// 复制为跨边界堆字符串 (size 为字节数, 不要求 NUL 结尾)
  int musicxx_extern_plugin_strdup_n(
    ffi.Pointer<MusicxxExternPluginStringView> src,
    ffi.Pointer<MusicxxExternPluginString> out,
  ) {
    return _musicxx_extern_plugin_strdup_n(src, out);
  }

  late final _musicxx_extern_plugin_strdup_nPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_strdup_n');
  late final _musicxx_extern_plugin_strdup_n =
      _musicxx_extern_plugin_strdup_nPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 释放宿主堆字符串 (幂等; NULL 安全)
  void musicxx_extern_plugin_string_free(
    ffi.Pointer<MusicxxExternPluginString> s,
  ) {
    return _musicxx_extern_plugin_string_free(s);
  }

  late final _musicxx_extern_plugin_string_freePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<MusicxxExternPluginString>)
        >
      >('musicxx_extern_plugin_string_free');
  late final _musicxx_extern_plugin_string_free =
      _musicxx_extern_plugin_string_freePtr
          .asFunction<void Function(ffi.Pointer<MusicxxExternPluginString>)>();

  /// C ABI 版本 (Dart 侧校验: 必须 == MUSICXX_EXTERN_PLUGIN_API_VERSION)
  int musicxx_extern_plugin_api_version() {
    return _musicxx_extern_plugin_api_version();
  }

  late final _musicxx_extern_plugin_api_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
        'musicxx_extern_plugin_api_version',
      );
  late final _musicxx_extern_plugin_api_version =
      _musicxx_extern_plugin_api_versionPtr.asFunction<int Function()>();

  /// 宿主库版本字符串 (形如 "1.0.0"); 写入 out (宿主堆, 需 string_free)
  int musicxx_extern_plugin_version(
    ffi.Pointer<MusicxxExternPluginString> out,
  ) {
    return _musicxx_extern_plugin_version(out);
  }

  late final _musicxx_extern_plugin_versionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<MusicxxExternPluginString>)
        >
      >('musicxx_extern_plugin_version');
  late final _musicxx_extern_plugin_version = _musicxx_extern_plugin_versionPtr
      .asFunction<int Function(ffi.Pointer<MusicxxExternPluginString>)>();

  /// 创建宿主 (纯构造, 不起线程/不加载插件); 失败返回 NULL 并写 log
  ffi.Pointer<MusicxxExternPluginHost> musicxx_extern_plugin_host_create(
    ffi.Pointer<MusicxxExternPluginHostConfig> cfg,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_host_create(cfg, log);
  }

  late final _musicxx_extern_plugin_host_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<MusicxxExternPluginHost> Function(
            ffi.Pointer<MusicxxExternPluginHostConfig>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_host_create');
  late final _musicxx_extern_plugin_host_create =
      _musicxx_extern_plugin_host_createPtr
          .asFunction<
            ffi.Pointer<MusicxxExternPluginHost> Function(
              ffi.Pointer<MusicxxExternPluginHostConfig>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 启动宿主: 起宿主线程/工作线程池、注册内置提供者、按配置装载插件
  /// - 就绪后入队 `musicxx.host.ready` 事件
  int musicxx_extern_plugin_host_start(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_host_start(h, log);
  }

  late final _musicxx_extern_plugin_host_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_host_start');
  late final _musicxx_extern_plugin_host_start =
      _musicxx_extern_plugin_host_startPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 同步停止 (幂等); 超时返回 MUSICXX_EXTERN_PLUGIN_ERR_TIMEOUT
  int musicxx_extern_plugin_host_stop(
    ffi.Pointer<MusicxxExternPluginHost> h,
    int timeout_ms,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_host_stop(h, timeout_ms, log);
  }

  late final _musicxx_extern_plugin_host_stopPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Uint32,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_host_stop');
  late final _musicxx_extern_plugin_host_stop =
      _musicxx_extern_plugin_host_stopPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              int,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 销毁宿主 (未停止会自动停止; NULL 安全)
  void musicxx_extern_plugin_host_destroy(
    ffi.Pointer<MusicxxExternPluginHost> h,
  ) {
    return _musicxx_extern_plugin_host_destroy(h);
  }

  late final _musicxx_extern_plugin_host_destroyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<MusicxxExternPluginHost>)
        >
      >('musicxx_extern_plugin_host_destroy');
  late final _musicxx_extern_plugin_host_destroy =
      _musicxx_extern_plugin_host_destroyPtr
          .asFunction<void Function(ffi.Pointer<MusicxxExternPluginHost>)>();

  /// 热更新语言 (插件可读; 插件侧 `pluginxx.config` 表 get_language)
  int musicxx_extern_plugin_set_language(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> lang,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_set_language(h, lang, log);
  }

  late final _musicxx_extern_plugin_set_languagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_set_language');
  late final _musicxx_extern_plugin_set_language =
      _musicxx_extern_plugin_set_languagePtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 热更新宿主配置 JSON (插件目录/开关/超时阈值/统计采集等)
  /// - 支持字段: pluginDirs[], enableNative, enableJs, safeMode, hookBudgetMs,
  /// hookHardBudgetMs, observeEvents, statsEnabled, statsPeriodMs
  int musicxx_extern_plugin_set_config(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_set_config(h, json, log);
  }

  late final _musicxx_extern_plugin_set_configPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_set_config');
  late final _musicxx_extern_plugin_set_config =
      _musicxx_extern_plugin_set_configPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 注册唤醒回调 (原生事件入队时调用; 未注册时 Dart 侧退回定时轮询)
  int musicxx_extern_plugin_set_wake_callback(
    ffi.Pointer<MusicxxExternPluginHost> h,
    MusicxxExternPluginWakeFn fn,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _musicxx_extern_plugin_set_wake_callback(h, fn, user_data);
  }

  late final _musicxx_extern_plugin_set_wake_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            MusicxxExternPluginWakeFn,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('musicxx_extern_plugin_set_wake_callback');
  late final _musicxx_extern_plugin_set_wake_callback =
      _musicxx_extern_plugin_set_wake_callbackPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              MusicxxExternPluginWakeFn,
              ffi.Pointer<ffi.Void>,
            )
          >();

  /// 批量取事件 (JSON 数组字符串); 无事件返回 MUSICXX_EXTERN_PLUGIN_ERR_TIMEOUT
  int musicxx_extern_plugin_poll_events(
    ffi.Pointer<MusicxxExternPluginHost> h,
    int max_count,
    ffi.Pointer<MusicxxExternPluginString> out_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_poll_events(h, max_count, out_json, log);
  }

  late final _musicxx_extern_plugin_poll_eventsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Int32,
            ffi.Pointer<MusicxxExternPluginString>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_poll_events');
  late final _musicxx_extern_plugin_poll_events =
      _musicxx_extern_plugin_poll_eventsPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              int,
              ffi.Pointer<MusicxxExternPluginString>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 宿主 → 插件事件总线发布 (topic 必须 musicxx.* 或 plugin.<id>.*)
  int musicxx_extern_plugin_event_publish(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> topic,
    ffi.Pointer<MusicxxExternPluginStringView> payload_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_event_publish(h, topic, payload_json, log);
  }

  late final _musicxx_extern_plugin_event_publishPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_event_publish');
  late final _musicxx_extern_plugin_event_publish =
      _musicxx_extern_plugin_event_publishPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 扫描插件目录 (用户目录 + 随包目录) + 内置清单 → JSON 数组
  int musicxx_extern_plugin_plugin_scan(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginString> out_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_plugin_scan(h, out_json, log);
  }

  late final _musicxx_extern_plugin_plugin_scanPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginString>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_plugin_scan');
  late final _musicxx_extern_plugin_plugin_scan =
      _musicxx_extern_plugin_plugin_scanPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginString>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 当前已加载插件状态快照 (JSON 数组)
  int musicxx_extern_plugin_plugin_list(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginString> out_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_plugin_list(h, out_json, log);
  }

  late final _musicxx_extern_plugin_plugin_listPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginString>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_plugin_list');
  late final _musicxx_extern_plugin_plugin_list =
      _musicxx_extern_plugin_plugin_listPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginString>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 异步装载 (结果经 `musicxx.plugin.loaded` / `musicxx.plugin.error` 事件回报)
  /// - `id_or_path` 可为插件 id 或插件目录/库文件路径
  /// - `options_json`: {"args":{...},"enabled":true,"tempDir":"...","kind":"native|js|builtin"}
  int musicxx_extern_plugin_plugin_load(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> id_or_path,
    ffi.Pointer<MusicxxExternPluginStringView> options_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_plugin_load(h, id_or_path, options_json, log);
  }

  late final _musicxx_extern_plugin_plugin_loadPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_plugin_load');
  late final _musicxx_extern_plugin_plugin_load =
      _musicxx_extern_plugin_plugin_loadPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 同步装载 (仅管理页/测试的隔离 isolate 使用; 带超时)
  int musicxx_extern_plugin_plugin_load_sync(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> id_or_path,
    ffi.Pointer<MusicxxExternPluginStringView> options_json,
    int timeout_ms,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_plugin_load_sync(
      h,
      id_or_path,
      options_json,
      timeout_ms,
      log,
    );
  }

  late final _musicxx_extern_plugin_plugin_load_syncPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Uint32,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_plugin_load_sync');
  late final _musicxx_extern_plugin_plugin_load_sync =
      _musicxx_extern_plugin_plugin_load_syncPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              int,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 启用 / 禁用 / 卸载 / 重载 (异步, 事件回报)
  int musicxx_extern_plugin_plugin_enable(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> id,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_plugin_enable(h, id, log);
  }

  late final _musicxx_extern_plugin_plugin_enablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_plugin_enable');
  late final _musicxx_extern_plugin_plugin_enable =
      _musicxx_extern_plugin_plugin_enablePtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  int musicxx_extern_plugin_plugin_disable(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> id,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_plugin_disable(h, id, log);
  }

  late final _musicxx_extern_plugin_plugin_disablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_plugin_disable');
  late final _musicxx_extern_plugin_plugin_disable =
      _musicxx_extern_plugin_plugin_disablePtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  int musicxx_extern_plugin_plugin_unload(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> id,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_plugin_unload(h, id, log);
  }

  late final _musicxx_extern_plugin_plugin_unloadPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_plugin_unload');
  late final _musicxx_extern_plugin_plugin_unload =
      _musicxx_extern_plugin_plugin_unloadPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  int musicxx_extern_plugin_plugin_reload(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> id,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_plugin_reload(h, id, log);
  }

  late final _musicxx_extern_plugin_plugin_reloadPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_plugin_reload');
  late final _musicxx_extern_plugin_plugin_reload =
      _musicxx_extern_plugin_plugin_reloadPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 更新插件参数 (需 reload 生效, 由 Dart 决定何时重载)
  int musicxx_extern_plugin_plugin_set_args(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> id,
    ffi.Pointer<MusicxxExternPluginStringView> args_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_plugin_set_args(h, id, args_json, log);
  }

  late final _musicxx_extern_plugin_plugin_set_argsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_plugin_set_args');
  late final _musicxx_extern_plugin_plugin_set_args =
      _musicxx_extern_plugin_plugin_set_argsPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 插件配置路径 (供管理页/插件读取); 未加载的插件按目录推导
  int musicxx_extern_plugin_plugin_get_config_path(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> id,
    ffi.Pointer<MusicxxExternPluginString> out,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_plugin_get_config_path(h, id, out, log);
  }

  late final _musicxx_extern_plugin_plugin_get_config_pathPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_plugin_get_config_path');
  late final _musicxx_extern_plugin_plugin_get_config_path =
      _musicxx_extern_plugin_plugin_get_config_pathPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 调用插件能力 (Dart → 插件; 同步带超时)
  /// - native/JS 插件统一用 `plugin.<pluginId>.<能力名>`
  int musicxx_extern_plugin_plugin_call(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> id,
    ffi.Pointer<MusicxxExternPluginStringView> method,
    ffi.Pointer<MusicxxExternPluginStringView> args_json,
    int timeout_ms,
    ffi.Pointer<MusicxxExternPluginString> out_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_plugin_call(
      h,
      id,
      method,
      args_json,
      timeout_ms,
      out_json,
      log,
    );
  }

  late final _musicxx_extern_plugin_plugin_callPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Uint32,
            ffi.Pointer<MusicxxExternPluginString>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_plugin_call');
  late final _musicxx_extern_plugin_plugin_call =
      _musicxx_extern_plugin_plugin_callPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              int,
              ffi.Pointer<MusicxxExternPluginString>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 派发钩子
  /// - `flags` = MUSICXX_EXTERN_PLUGIN_HOOK_SYNC 时等待处理器链 (预算内) 并输出合并结果;
  /// MUSICXX_EXTERN_PLUGIN_HOOK_ASYNC 时入队即返回 (out_json 为 {"handled":bool})
  /// - out_json 形如 {"handled":true,"result":{...},"timedOut":false,"handlers":2}
  int musicxx_extern_plugin_hook_emit(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> hook_id,
    ffi.Pointer<MusicxxExternPluginStringView> input_json,
    int flags,
    int timeout_ms,
    ffi.Pointer<MusicxxExternPluginString> out_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_hook_emit(
      h,
      hook_id,
      input_json,
      flags,
      timeout_ms,
      out_json,
      log,
    );
  }

  late final _musicxx_extern_plugin_hook_emitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Int32,
            ffi.Uint32,
            ffi.Pointer<MusicxxExternPluginString>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_hook_emit');
  late final _musicxx_extern_plugin_hook_emit =
      _musicxx_extern_plugin_hook_emitPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              int,
              int,
              ffi.Pointer<MusicxxExternPluginString>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 该钩子当前的原生/JS 处理器数量 (Dart 快速路径判定; 事件增量更新)
  int musicxx_extern_plugin_hook_count(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> hook_id,
    ffi.Pointer<ffi.Int32> out_count,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_hook_count(h, hook_id, out_count, log);
  }

  late final _musicxx_extern_plugin_hook_countPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_hook_count');
  late final _musicxx_extern_plugin_hook_count =
      _musicxx_extern_plugin_hook_countPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<ffi.Int32>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 钩子耗时/超时/失败统计 (调试页)
  int musicxx_extern_plugin_hook_stats(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginString> out_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_hook_stats(h, out_json, log);
  }

  late final _musicxx_extern_plugin_hook_statsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginString>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_hook_stats');
  late final _musicxx_extern_plugin_hook_stats =
      _musicxx_extern_plugin_hook_statsPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginString>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 回复插件发起的动作请求 (status 见错误码; result_json 可为空)
  int musicxx_extern_plugin_action_respond(
    ffi.Pointer<MusicxxExternPluginHost> h,
    int request_id,
    int status,
    ffi.Pointer<MusicxxExternPluginStringView> result_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_action_respond(
      h,
      request_id,
      status,
      result_json,
      log,
    );
  }

  late final _musicxx_extern_plugin_action_respondPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Int64,
            ffi.Int32,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_action_respond');
  late final _musicxx_extern_plugin_action_respond =
      _musicxx_extern_plugin_action_respondPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              int,
              int,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 推送单个状态键 (值必须为合法 JSON; 单键上限 64 KiB, 超出截断并告警)
  int musicxx_extern_plugin_state_update(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> key,
    ffi.Pointer<MusicxxExternPluginStringView> value_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_state_update(h, key, value_json, log);
  }

  late final _musicxx_extern_plugin_state_updatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_state_update');
  late final _musicxx_extern_plugin_state_update =
      _musicxx_extern_plugin_state_updatePtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 批量推送状态键: [{"key":"...","value":{...}}, ...]
  int musicxx_extern_plugin_state_update_batch(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> items_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_state_update_batch(h, items_json, log);
  }

  late final _musicxx_extern_plugin_state_update_batchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_state_update_batch');
  late final _musicxx_extern_plugin_state_update_batch =
      _musicxx_extern_plugin_state_update_batchPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 插件贡献的 UI 项快照 (JSON 数组; 变更另有 musicxx.ui.changed 事件)
  int musicxx_extern_plugin_ui_snapshot(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginString> out_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_ui_snapshot(h, out_json, log);
  }

  late final _musicxx_extern_plugin_ui_snapshotPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginString>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_ui_snapshot');
  late final _musicxx_extern_plugin_ui_snapshot =
      _musicxx_extern_plugin_ui_snapshotPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginString>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// Dart → 原生日志 (统一落盘/转发; level: 0 trace .. 4 error)
  int musicxx_extern_plugin_log(
    ffi.Pointer<MusicxxExternPluginHost> h,
    int level,
    ffi.Pointer<MusicxxExternPluginStringView> message,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_log(h, level, message, log);
  }

  late final _musicxx_extern_plugin_logPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Int32,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_log');
  late final _musicxx_extern_plugin_log = _musicxx_extern_plugin_logPtr
      .asFunction<
        int Function(
          ffi.Pointer<MusicxxExternPluginHost>,
          int,
          ffi.Pointer<MusicxxExternPluginStringView>,
          ffi.Pointer<MusicxxExternPluginString>,
        )
      >();

  /// 调试信息 (版本/依赖/平台/插件统计; 支持页复制)
  int musicxx_extern_plugin_debug_info(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginString> out_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_debug_info(h, out_json, log);
  }

  late final _musicxx_extern_plugin_debug_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginString>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_debug_info');
  late final _musicxx_extern_plugin_debug_info =
      _musicxx_extern_plugin_debug_infoPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginString>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();

  /// 资源与耗时统计快照 (scope_json = NULL 取全部)
  int musicxx_extern_plugin_stats(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> scope_json,
    ffi.Pointer<MusicxxExternPluginString> out_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_stats(h, scope_json, out_json, log);
  }

  late final _musicxx_extern_plugin_statsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_stats');
  late final _musicxx_extern_plugin_stats = _musicxx_extern_plugin_statsPtr
      .asFunction<
        int Function(
          ffi.Pointer<MusicxxExternPluginHost>,
          ffi.Pointer<MusicxxExternPluginStringView>,
          ffi.Pointer<MusicxxExternPluginString>,
          ffi.Pointer<MusicxxExternPluginString>,
        )
      >();

  /// 统计采集配置 ({"enable":bool,"jsHeapSampleMs":int,"observeEvents":bool})
  int musicxx_extern_plugin_stats_config(
    ffi.Pointer<MusicxxExternPluginHost> h,
    ffi.Pointer<MusicxxExternPluginStringView> cfg_json,
    ffi.Pointer<MusicxxExternPluginString> log,
  ) {
    return _musicxx_extern_plugin_stats_config(h, cfg_json, log);
  }

  late final _musicxx_extern_plugin_stats_configPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<MusicxxExternPluginHost>,
            ffi.Pointer<MusicxxExternPluginStringView>,
            ffi.Pointer<MusicxxExternPluginString>,
          )
        >
      >('musicxx_extern_plugin_stats_config');
  late final _musicxx_extern_plugin_stats_config =
      _musicxx_extern_plugin_stats_configPtr
          .asFunction<
            int Function(
              ffi.Pointer<MusicxxExternPluginHost>,
              ffi.Pointer<MusicxxExternPluginStringView>,
              ffi.Pointer<MusicxxExternPluginString>,
            )
          >();
}

/// 只读借用字符串视图 (指向调用方内存, UTF-8, 不要求 NUL 结尾)
final class MusicxxExternPluginStringView extends ffi.Struct {
  external ffi.Pointer<ffi.Char> data;

  @ffi.Uint64()
  external int size;
}

/// 宿主堆分配字符串 (显式所有权: 由宿主分配, 调用方用 string_free 释放)
final class MusicxxExternPluginString extends ffi.Struct {
  /// < 以 \0 结尾; 空串或未设置时为 NULL
  external ffi.Pointer<ffi.Char> data;

  /// < 字节数 (不含结尾 \0)
  @ffi.Uint64()
  external int size;
}

final class MusicxxExternPluginHost extends ffi.Opaque {}

final class MusicxxExternPluginHostConfig extends ffi.Struct {
  /// < == sizeof(MusicxxExternPluginHostConfig)
  @ffi.Uint32()
  external int struct_size;

  /// < 应用版本 (如 "0.87.0")
  external MusicxxExternPluginStringView app_version;

  /// < 平台标识 (windows/linux/macos/android/ios/ohos)
  external MusicxxExternPluginStringView platform;

  /// < 语言代码 (如 "zh-cn")
  external MusicxxExternPluginStringView language;

  /// < 用户插件目录 (绝对路径; 可为空)
  external MusicxxExternPluginStringView user_plugin_dir;

  /// < 随包插件目录 (绝对路径; 可为空)
  external MusicxxExternPluginStringView builtin_plugin_dir;

  /// < 插件私有数据根目录 (绝对路径; 可为空)
  external MusicxxExternPluginStringView data_dir;

  /// < 日志目录 (绝对路径; 可为空)
  external MusicxxExternPluginStringView log_dir;

  /// < 0 trace .. 4 error
  @ffi.Int32()
  external int log_level;

  /// < MUSICXX_EXTERN_PLUGIN_FLAG_*
  @ffi.Int32()
  external int flags;

  /// < 0 = 默认 16384
  @ffi.Uint32()
  external int event_queue_capacity;
}

/// 事件唤醒回调 (原生事件入队时调用; 必须快速返回)
typedef MusicxxExternPluginWakeFn =
    ffi.Pointer<ffi.NativeFunction<MusicxxExternPluginWakeFnFunction>>;
typedef MusicxxExternPluginWakeFnFunction =
    ffi.Int32 Function(ffi.Pointer<ffi.Void> user_data);
typedef DartMusicxxExternPluginWakeFnFunction =
    int Function(ffi.Pointer<ffi.Void> user_data);
